# Artificial Neural Network

Udemy Course : Artificial Neural Network For Regression 
Build an ANN Regression model to predict the electrical energy output of a Combined Cycle Power Plant

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 176120.0070
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 20657.3196
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 436.1127
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 436.3554
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 433.7094
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 410.6000
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 398.9604
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 378.3524
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 370.3897
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 348.2895
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 332.7624
Epoch 12/100
240/240 [==============================] - 0s 1ms/step -

### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)
y_pred

array([[431.72],
       [463.  ],
       [466.6 ],
       ...,
       [473.65],
       [440.74],
       [459.83]], dtype=float32)

In [15]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [18]:
y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)

(array([[431.72],
        [463.  ],
        [466.6 ],
        ...,
        [473.65],
        [440.74],
        [459.83]], dtype=float32), array([[431.23],
        [460.01],
        [461.14],
        ...,
        [473.26],
        [438.  ],
        [463.28]]))

In [12]:
np.set_printoptions(precision=2) # 2 decimal
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.72 431.23]
 [463.   460.01]
 [466.6  461.14]
 ...
 [473.65 473.26]
 [440.74 438.  ]
 [459.83 463.28]]
